name: checks

on:
  push:
    tags:
     - v\d+.\d+.\d+
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
         node-version: '18.x'
      - name: Test Build
        run: |
          cd website
          if [-e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [-e package.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
